In [31]:
# private_key = {
#   "type": "service_account",
#   "project_id": "geoapp-1332",
#   "private_key_id": "678836e3dffc042fa20847b376f1f074259ea889",
#   "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCVZimWdeheqe2f\n3dFoP7qX6LmGHHIQXCru3HennOJH6MBHu8rfORJHic3nTDsinCr0YKUq8S3d4o0W\n9/IDJS1dhyfoVKRTlzVv9jd4cd/bMNQuHAsS8ICTrudTsJ2vwymdzXpfO3sxL+Ru\nCuYZrqPd0l+u36sIt4sSatqB/XlysB/h4Tg0SXoa7gVj6Nq+sLTfl2EyfqF/3n8L\n6b/NmBU4tkhp86lud7y5aiMN7VB9P0jzSLvsBky/orDKefsBXBbXuOh0vQD0OStX\nPKg3oVBKBffyR1wL+6TP/sKkio18WGdw78dc5/Q2bEw8Zf+oHgES+Cq0zKeLgr+f\nUowktRX5AgMBAAECggEAJDmwbdZLMOD9SF1N0Hxbb0gz7AvrsIHYuzBkJxVIXO1X\n6kzjxTqebxBACAyY7ix10em5Qu9WEs5DLcWTPiX+mQYTrCcR7V7lyy8lhiP+hrSR\nTljoaoA8fRLU7psNsTeeWLAhMwRGO8gEGJa18pZBD6FaKBn969AtfZrBPvHKR/+D\nuyk1louLIIfYiDZyOz3wluDsNXu11quEAqrYKZ8OKt6I38+/51cKl2YH2sRyHjKo\nF3+5lVZ5uTmQpVfQngWGPExv4vDpJ90VMDIeTMf4B6eMSxymE1fKhoDbv1eANCYt\nAizfKE9kLm6zoULEi9cLz9UZZGYBnighJF7Fd3YeHQKBgQDRc/AMAxeiDhwwceG3\nRz6JGRD/z+XhEqan3qwmnvFRMhzhJDb6qim97gmZBCTt5zeJABiDWhhmDssN5AAJ\n5mmXDGp22uxiW6pb1JtzGOUmIwbFWwtTh26BqBiVLxbg+tjAG+ErRJqOQOtLbUun\nZPEyimPfunHCdQXo81jt//wWXwKBgQC2ma5WWvcUs7uyLf0ccqBcQK1Itu65ZYtP\nbtujQmohzUT58jKs0OtjfUh7uEt40sBlIwVqgl3IR8k4XjZxTyw7fd9EdIpMhTjp\nnqO+rszXXtLtyqAi35sTCpbdgL2kGioj+9v80J8I2PWWoVhGFLBZNUsWKYSaTcOm\n9nfKu0JCpwKBgQDKmcvrwp38mot37OB56Yc7FC0WVWI2WVUtcj2xSfOBJ+k5ek9Y\nHnssBfHwukqCeTKF6brMa7zIE60kbZP//4nJmy/scg1Pgv2BwGDxb3ZQcncdNdj5\n3jntXs0QmTEXRG2fPhiLQtwBmBhBqKISdJi+25CKHA3oHEwwLhuqc//DHwKBgQCJ\nZZAB2IasZCVqiCI5YqL5Z4079rIgfKDbjz3jVZkIgC1TqYOp97X28ZE1ztGzQ1mT\ngEuV/ixVBHcLXBC5J+rPhQIXv11FAMV3PHBXja4CrI4ocVwXgYttQ32LhFCuByYI\nV34LeGsCPEZnJlaGvRCIv4oVTf5CIRuEKVawDEFqZwKBgGeJFVsjWdZP9EmTudP1\nPAMe1dTyXpGHdJgunp0D5B1aTKdJwPzo4lGw2Sh1c55rpRwtzguzk7cdOzXNKuZA\nrlxYRXIbBVjHbUw+mhVKL57u6JbSU6khVN2CusQz3ZyyhWlZZYUgPrAc3pgyZrKa\nr9GD+J4GMxMU3lNxlfmSqcoz\n-----END PRIVATE KEY-----\n",
#   "client_email": "559371379291-compute@developer.gserviceaccount.com",
#   "client_id": "108723000884014830663",
#   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
#   "token_uri": "https://accounts.google.com/o/oauth2/token",
#   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
#   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/559371379291-compute%40developer.gserviceaccount.com"
# }

# accident.to_gbq(
#   destination_table=u'nispc.accident',
#   project_id='geoapp-1332',
#   private_key=json.dumps(private_key), 
# )

# pd.read_gbq('select * from nispc.accident', project_id='geoapp-1332', private_key=json.dumps(private_key))

In [11]:
import geopandas as gpd

In [12]:
import gcp.storage as storage

In [13]:
bucket = storage.Bucket('geoapp-1332-datalab')

In [14]:
%%storage list -p geoapp-1332

In [15]:
# %%storage list -b gs://geoapp-1332-datalab

In [16]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/99y.csv --variable accident_99

In [17]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/100y.csv --variable accident_100

In [18]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/101y.csv --variable accident_101

In [19]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/102y.csv --variable accident_102

In [26]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/99y_twd97.csv --variable accident_99_loc

In [27]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/100y_twd97.csv --variable accident_100_loc

In [28]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/101y_twd97.csv --variable accident_101_loc

In [29]:
%%storage read --object gs://geoapp-1332-datalab/20151114\ Accident/102y_twd97.csv --variable accident_102_loc

In [20]:
import pandas as pd
from StringIO import StringIO
import json

In [30]:
accident_100 = pd.read_csv(StringIO(accident_100))
accident_101 = pd.read_csv(StringIO(accident_101))
accident_102 = pd.read_csv(StringIO(accident_102))
accident_99 = pd.read_csv(StringIO(accident_99))
accident_100_loc = pd.read_csv(StringIO(accident_100_loc))
accident_101_loc = pd.read_csv(StringIO(accident_101_loc))
accident_102_loc = pd.read_csv(StringIO(accident_102_loc))
accident_99_loc = pd.read_csv(StringIO(accident_99_loc))

In [22]:
accident = pd.concat([accident_99, accident_100, accident_101, accident_102])

In [40]:
accident = accident.set_index('CASE_NO')

In [41]:
accident_loc = pd.concat([accident_99_loc, accident_100_loc, accident_101_loc, accident_102_loc])

In [42]:
accident_loc = accident_loc.set_index('CASE_NO')

In [47]:
accident_loc = accident_loc[['x_coord', 'y_coord']]

In [48]:
accident = accident.join(accident_loc)

In [53]:
accident 

ACCD_TP Sub_bur     Eve_time  YEAR  MONTH  HOUR  Two_HOUR  \
CASE_NO                                                               
C5002982        2      C5   9912011125    99     12    11         6   
C5002982        2      C5   9912011125    99     12    11         6   
C5002982        2      C5   9912011125    99     12    11         6   
C5101541        2      C5   9902111400    99      2    14         8   
C5101543        2      C5   9903031745    99      3    17         9   
C5101543        2      C5   9903031745    99      3    17         9   
C5101554        2      C5   9908180730    99      8     7         4   
C5101554        2      C5   9908180730    99      8     7         4   
C5103031        2      C5  10203161723   102      3    17         9   
C5103031        2      C5  10203161723   102      3    17         9   
C5103031        2      C5  10203161723   102      3    17         9   
C5103033        2      C5  10203171431   102      3    14         8   
C5103033        2      C5  10203171431   102      3    14         8   
C5103034        2      C5  10203171655   102      3    16         9   
C5103034        2      C5  10203171655   102      3    16         9   
C5103035        2      C5  10203180750   102      3     7         4   
C5103035        2      C5  10203180750   102      3     7         4   
C5103037        2      C5  10203200930   102      3     9         5   
C5103037        2      C5  10203200930   102      3     9         5   
C5103038        2      C5  10203210650   102      3     6         4   
C5103038        2      C5  10203210650   102      3     6         4   
C5103061        2      C5  10203121755   102      3    17         9   
C5103063        2      C5  10203162012   102      3    20        11   
C5103063        2      C5  10203162012   102      3    20        11   
C5103068        2      C5  10203191345   102      3    13         7   
C5103068        2      C5  10203191345   102      3    13         7   
C5103070        2      C5  10203231035   102      3    10         6   
C5103070        2      C5  10203231035   102      3    10         6   
C5103073        2      C5  10203272343   102      3    23        12   
C5103073        2      C5  10203272343   102      3    23        12   
...           ...     ...          ...   ...    ...   ...       ...   
CI900544        2      CI  10204221520   102      4    15         8   
CI900547        2      CI  10204240730   102      4     7         4   
CI900547        2      CI  10204240730   102      4     7         4   
CI900550        2      CI  10204281629   102      4    16         9   
CI900550        2      CI  10204281629   102      4    16         9   
CI900553        2      CI  10204300830   102      4     8         5   
CI900553        2      CI  10204300830   102      4     8         5   
CI900553        2      CI  10204300830   102      4     8         5   
CI900554        2      CI  10205031523   102      5    15         8   
CI900555        2      CI  10205032250   102      5    22        12   
CI900555        2      CI  10205032250   102      5    22        12   
CI900559        2      CI  10205101610   102      5    16         9   
CI900559        2      CI  10205101610   102      5    16         9   
CI900560        2      CI  10205111140   102      5    11         6   
CI900560        2      CI  10205111140   102      5    11         6   
CI900561        2      CI  10205150810   102      5     8         5   
CI900561        2      CI  10205150810   102      5     8         5   
CI900562        2      CI  10205171330   102      5    13         7   
CI900562        2      CI  10205171330   102      5    13         7   
CI900576        2      CI  10204101530   102      4    15         8   
CI900576        2      CI  10204101530   102      4    15         8   
CI900576        2      CI  10204101530   102      4    15         8   
CI900582        2      CI  10204282250   102      4    22        12   
CI900582        2      CI  1020428

In [54]:
len(accident.index.unique())

73214

In [55]:
from shapely.ops import nearest_points

In [80]:
from shapely.geometry import Point, MultiLineString

In [85]:
coords = [((0, 0), (1, 1)), ((-1, 0), (1, 0))]
lineString = MultiLineString(coords)

In [86]:
point = Point(1, 1.2)

In [87]:
nearest_points(lineString, point)[0].x, nearest_points(lineString, point)[0].y

(1.0, 1.0)

In [91]:
nearest_points(lineString, point)[1].x, nearest_points(lineString, point)[1].y

(1.0, 1.2)

In [92]:
from sklearn.neighbors.kde import KernelDensity

In [93]:
import numpy as np

In [212]:
X = np.array([[0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0]])

In [213]:
X

array([[0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0]])

In [214]:
kde = KernelDensity(kernel='tophat', bandwidth=0.1).fit(X)

In [219]:
kde.score_samples(X)

array([ 43.94579018])

In [136]:
X

array([[-3, -2],
       [-2, -1],
       [-1, -1],
       [ 1,  1],
       [ 2,  1],
       [ 3,  2]])

In [208]:
X = np.concatenate((np.random.normal(0, 1, 0.3 * N),
                    np.random.normal(5, 1, 0.7 * N)))[:, np.newaxis]
X_plot = np.linspace(-5, 10, 1000)[:, np.newaxis]

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


In [222]:
kde = KernelDensity(kernel='tophat', bandwidth=0.75).fit(X)

In [221]:
kde.

array([[0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0]])

In [211]:
np.exp(kde.score_samples(X))

array([ 0.12666667,  0.1       ,  0.08      ,  0.09333333,  0.12      ,
        0.09333333,  0.02666667,  0.13333333,  0.12666667,  0.08666667,
        0.11333333,  0.06666667,  0.12666667,  0.12666667,  0.12666667,
        0.12      ,  0.09333333,  0.13333333,  0.04      ,  0.09333333,
        0.12666667,  0.01333333,  0.13333333,  0.14      ,  0.11333333,
        0.1       ,  0.08      ,  0.11333333,  0.06666667,  0.03333333,
        0.14      ,  0.09333333,  0.09333333,  0.19333333,  0.17333333,
        0.06666667,  0.20666667,  0.13333333,  0.14666667,  0.21333333,
        0.15333333,  0.18      ,  0.18      ,  0.21333333,  0.12666667,
        0.24666667,  0.08666667,  0.2       ,  0.1       ,  0.24      ,
        0.15333333,  0.04      ,  0.20666667,  0.21333333,  0.2       ,
        0.21333333,  0.23333333,  0.24      ,  0.18      ,  0.08      ,
        0.22666667,  0.15333333,  0.16666667,  0.2       ,  0.09333333,
        0.18666667,  0.21333333,  0.21333333,  0.23333333,  0.12

In [230]:
from sklearn.neighbors.kde import KernelDensity
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
kde = KernelDensity(kernel='gaussian', bandwidth=2).fit(X)
kde.score_samples(X)

array([-3.90852856, -3.93258163, -4.15145283, -3.90852856, -3.93258163,
       -4.15145283])

In [231]:
np.exp(kde.score_samples(X))

array([ 0.02007001,  0.01959303,  0.01574153,  0.02007001,  0.01959303,
        0.01574153])

In [232]:
X = np.concatenate((np.random.normal(0, 1, 0.3 * N),
                    np.random.normal(5, 1, 0.7 * N)))

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':
/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


In [237]:
X

array([ 0.04366899, -0.22631424,  1.33145711, -0.28730786,  0.68006984,
       -0.3198016 , -1.27255876,  0.31354772,  0.50318481,  1.29322588,
       -0.11044703, -0.61736206,  0.5627611 ,  0.24073709,  0.28066508,
       -0.0731127 ,  1.16033857,  0.36949272,  1.90465871,  1.1110567 ,
        0.6590498 , -1.62743834,  0.60231928,  0.4202822 ,  0.81095167,
        1.04444209, -0.40087819,  0.82400562, -0.56230543,  1.95487808,
        3.66804833,  3.23931144,  3.34927873,  4.10944442,  3.8808846 ,
        6.9560789 ,  4.6735005 ,  3.65732421,  6.11438298,  4.41347606,
        3.76314662,  5.87583893,  5.62336218,  4.56504332,  6.40754   ,
        5.12910158,  6.6169496 ,  5.50274088,  6.55880554,  5.1094027 ,
        3.7802556 ,  7.44936865,  4.45422583,  4.80116214,  4.2996015 ,
        4.79660555,  5.24266944,  5.20183018,  5.66102029,  6.79215821,
        4.87953543,  3.76687926,  3.81768187,  4.33424548,  3.32580419,
        5.82502982,  4.50178644,  4.68901502,  4.99810852,  3.60

In [234]:
X[:, np.newaxis]

array([[ 0.04366899],
       [-0.22631424],
       [ 1.33145711],
       [-0.28730786],
       [ 0.68006984],
       [-0.3198016 ],
       [-1.27255876],
       [ 0.31354772],
       [ 0.50318481],
       [ 1.29322588],
       [-0.11044703],
       [-0.61736206],
       [ 0.5627611 ],
       [ 0.24073709],
       [ 0.28066508],
       [-0.0731127 ],
       [ 1.16033857],
       [ 0.36949272],
       [ 1.90465871],
       [ 1.1110567 ],
       [ 0.6590498 ],
       [-1.62743834],
       [ 0.60231928],
       [ 0.4202822 ],
       [ 0.81095167],
       [ 1.04444209],
       [-0.40087819],
       [ 0.82400562],
       [-0.56230543],
       [ 1.95487808],
       [ 3.66804833],
       [ 3.23931144],
       [ 3.34927873],
       [ 4.10944442],
       [ 3.8808846 ],
       [ 6.9560789 ],
       [ 4.6735005 ],
       [ 3.65732421],
       [ 6.11438298],
       [ 4.41347606],
       [ 3.76314662],
       [ 5.87583893],
       [ 5.62336218],
       [ 4.56504332],
       [ 6.40754   ],
       [ 5

In [235]:
X_plot = np.linspace(-5, 10, 1000)[:, np.newaxis]

In [238]:
len(X_plot)

1000

In [239]:
X_plot

array([[ -5.        ],
       [ -4.98498498],
       [ -4.96996997],
       [ -4.95495495],
       [ -4.93993994],
       [ -4.92492492],
       [ -4.90990991],
       [ -4.89489489],
       [ -4.87987988],
       [ -4.86486486],
       [ -4.84984985],
       [ -4.83483483],
       [ -4.81981982],
       [ -4.8048048 ],
       [ -4.78978979],
       [ -4.77477477],
       [ -4.75975976],
       [ -4.74474474],
       [ -4.72972973],
       [ -4.71471471],
       [ -4.6996997 ],
       [ -4.68468468],
       [ -4.66966967],
       [ -4.65465465],
       [ -4.63963964],
       [ -4.62462462],
       [ -4.60960961],
       [ -4.59459459],
       [ -4.57957958],
       [ -4.56456456],
       [ -4.54954955],
       [ -4.53453453],
       [ -4.51951952],
       [ -4.5045045 ],
       [ -4.48948949],
       [ -4.47447447],
       [ -4.45945946],
       [ -4.44444444],
       [ -4.42942943],
       [ -4.41441441],
       [ -4.3993994 ],
       [ -4.38438438],
       [ -4.36936937],
       [ -4